/*
 * MorphIt C API: approximate a triangle mesh with spheres.
 *
 * Threading: every function may be called from any thread. Sessions are
 * independent and may run concurrently. On one session the read functions
 * (morphit_state, morphit_get_*, morphit_result_*) and morphit_cancel may be
 * called while morphit_run is active on another thread; they never wait for
 * an iteration to finish. morphit_step, morphit_run, morphit_finalize and
 * morphit_session_free return MORPHIT_ERR_BUSY while a run is active.
 *
 * Errors: functions return morphit_status; morphit_last_error() gives a
 * message for the last failed call on the calling thread.
 *
 * Buffers: array/string outputs take (buffer, capacity, size_out). Passing
 * NULL with capacity 0 queries the size.
 */

#ifndef MORPHIT_H
#define MORPHIT_H

/* Generated by cbindgen from crates/morphit-capi/src. Do not edit by hand. */

#include <stddef.h>
#include <stdint.h>

/**
 * Number of entries in the per-loss arrays of `morphit_step_info`.
 */
#define MORPHIT_LOSS_COUNT 12

/**
 * Result of every fallible call. Negative values are errors; call
 * `morphit_last_error()` on the same thread for a message.
 */
typedef enum morphit_status {
  /**
   * Success.
   */
  MORPHIT_OK = 0,
  /**
   * `morphit_step`: the session has no iterations left; nothing was run.
   */
  MORPHIT_DONE = 1,
  /**
   * A required pointer argument was NULL.
   */
  MORPHIT_ERR_NULL_ARG = -1,
  /**
   * An argument was invalid (bad UTF-8, zero count, out-of-range index, ...).
   */
  MORPHIT_ERR_INVALID_ARG = -2,
  /**
   * A file could not be read or written.
   */
  MORPHIT_ERR_IO = -3,
  /**
   * The mesh could not be parsed or is unusable.
   */
  MORPHIT_ERR_MESH = -4,
  /**
   * Unknown preset or key, wrong value type, or invalid value.
   */
  MORPHIT_ERR_CONFIG = -5,
  /**
   * Operation not valid in the session's current state.
   */
  MORPHIT_ERR_STATE = -6,
  /**
   * `morphit_run` is active on this session (from another thread or from
   * inside its own progress callback).
   */
  MORPHIT_ERR_BUSY = -7,
  /**
   * The run was cancelled by `morphit_cancel` or the progress callback.
   */
  MORPHIT_ERR_CANCELLED = -8,
  /**
   * The output buffer is too small; the required size was reported.
   */
  MORPHIT_ERR_BUFFER_TOO_SMALL = -9,
  /**
   * An internal error (Rust panic) was caught at the API boundary.
   */
  MORPHIT_ERR_PANIC = -10,
  /**
   * The worker thread pool is already running and cannot be reconfigured.
   */
  MORPHIT_ERR_THREADPOOL = -11,
} morphit_status;

/**
 * Lifecycle of a session.
 */
typedef enum morphit_session_state {
  /**
   * Iterations remain.
   */
  MORPHIT_STATE_RUNNING = 0,
  /**
   * Stopped early by the convergence test (`training.early_stopping`).
   */
  MORPHIT_STATE_CONVERGED = 1,
  /**
   * All configured iterations ran.
   */
  MORPHIT_STATE_COMPLETED = 2,
  /**
   * The final escaped-sphere prune ran; the result is final.
   */
  MORPHIT_STATE_FINALIZED = 3,
} morphit_session_state;

/**
 * Loss term indices into `morphit_step_info::weighted_losses` / `raw_losses`.
 */
typedef enum morphit_loss_id {
  MORPHIT_LOSS_COVERAGE = 0,
  MORPHIT_LOSS_OVERLAP = 1,
  MORPHIT_LOSS_BOUNDARY = 2,
  MORPHIT_LOSS_SURFACE = 3,
  MORPHIT_LOSS_CONTAINMENT = 4,
  MORPHIT_LOSS_SQEM = 5,
  MORPHIT_LOSS_HAUSDORFF = 6,
  MORPHIT_LOSS_MESH_CONTAINMENT = 7,
  MORPHIT_LOSS_MASS = 8,
  MORPHIT_LOSS_COM = 9,
  MORPHIT_LOSS_INERTIA = 10,
  /**
   * Not implemented; always 0.
   */
  MORPHIT_LOSS_FLATNESS = 11,
} morphit_loss_id;

/**
 * Mutable configuration. Setters lock internally, so a config may be edited
 * and read from several threads; sessions copy it on creation.
 */
typedef struct morphit_config morphit_config;

/**
 * Immutable mesh, shareable by any number of sessions and threads.
 */
typedef struct morphit_mesh morphit_mesh;

/**
 * A robot description package (URDF plus meshes) held in memory, and the
 * sphere results recorded for its links. Locks internally; may be used from
 * several threads.
 */
typedef struct morphit_robot morphit_robot;

/**
 * The inspection of one URDF: every `<collision>` and what to do with it.
 * Immutable. The "pack items" are the collisions to replace with spheres,
 * numbered `0 .. morphit_report_pack_count()`.
 */
typedef struct morphit_robot_report morphit_robot_report;

/**
 * A packing session. See the module docs for the locking scheme.
 */
typedef struct morphit_session morphit_session;

/**
 * Receives one formatted log line. `level`: 1 = error, 2 = warn, 3 = info,
 * 4 = debug, 5 = trace. `message` is only valid during the call.
 */
typedef void (*morphit_log_fn)(int level, const char *message, void *user_data);

/**
 * Mesh properties.
 */
typedef struct morphit_mesh_info {
  size_t num_vertices;
  size_t num_faces;
  double volume;
  double area;
  /**
   * Length of the bounding-box diagonal.
   */
  double scale;
  double bounds_min[3];
  double bounds_max[3];
  double center_mass[3];
  /**
   * Inertia tensor about the center of mass at density 1, row-major.
   */
  double inertia[9];
  /**
   * Nonzero if the input was wound inward and all faces were flipped.
   */
  int32_t winding_flipped;
} morphit_mesh_info;

/**
 * What one iteration did.
 */
typedef struct morphit_step_info {
  /**
   * Zero-based index of the iteration that ran.
   */
  uint64_t iteration;
  double total_loss;
  /**
   * `weight * value` per loss, indexed by `morphit_loss_id`.
   */
  double weighted_losses[MORPHIT_LOSS_COUNT];
  /**
   * Unweighted value per loss, indexed by `morphit_loss_id`.
   */
  double raw_losses[MORPHIT_LOSS_COUNT];
  /**
   * Mean per-sphere center-gradient norm before clipping.
   */
  double position_grad_mag;
  /**
   * Raw-radius gradient norm before clipping.
   */
  double radius_grad_mag;
  size_t num_spheres;
  /**
   * Centers projected back inside the mesh during this iteration.
   */
  size_t projected;
  /**
   * Nonzero if density control ran after this iteration.
   */
  int32_t density_control_fired;
  /**
   * Spheres culled and reseeded by density control (0 if it did not run).
   */
  size_t density_control_replaced;
  /**
   * Nonzero when the session has no iterations left.
   */
  int32_t done;
  /**
   * Nonzero when the convergence test stopped the run here.
   */
  int32_t converged;
  double seconds;
} morphit_step_info;

/**
 * Called after every iteration of `morphit_run` with no locks held. Return
 * nonzero to cancel the run. `info` is only valid during the call.
 */
typedef int (*morphit_progress_fn)(const struct morphit_step_info *info, void *user_data);

/**
 * Session progress, readable at any time from any thread.
 */
typedef struct morphit_state_info {
  enum morphit_session_state state;
  /**
   * Iterations run so far.
   */
  uint64_t iteration;
  uint64_t total_iterations;
  size_t num_spheres;
  /**
   * Loss of the last iteration (NaN before the first).
   */
  double total_loss;
  /**
   * Nonzero while `morphit_run` is active.
   */
  int32_t running;
  uint64_t density_control_passes;
  /**
   * Spheres removed by the final prune.
   */
  size_t pruned;
  /**
   * Seed that drove all sampling (drawn at random when the config had none).
   */
  uint64_t seed;
} morphit_state_info;

/**
 * Options of `morphit_object_urdf` / `morphit_object_mjcf`. Fill with
 * `morphit_object_options_default`, then change fields.
 */
typedef struct morphit_object_options {
  /**
   * `<robot name>` / `<mujoco model>`; NULL means "object".
   */
  const char *name;
  /**
   * Sphere color, RGBA in 0..1.
   */
  double rgba[4];
  /**
   * Total mass in kg, split over the spheres in proportion to r^3.
   */
  double total_mass;
  /**
   * Nonzero welds the object to the world instead of letting it float.
   */
  int anchored;
  /**
   * Decimal places of every number written.
   */
  int decimals;
} morphit_object_options;

/**
 * Sampling settings of `morphit_evaluate_packing` (defaults match the
 * Python `debug_quick_eval.py`).
 */
typedef struct morphit_quality_options {
  uint64_t seed;
  size_t surface_samples;
  size_t volume_samples;
  /**
   * Volume samples come from the mesh bounding box scaled by this factor.
   */
  double bounds_expand;
  /**
   * Density used for the sphere masses when none are given.
   */
  double density;
} morphit_quality_options;

/**
 * Quality of a packing (the `debug_quick_eval` metrics).
 */
typedef struct morphit_quality_metrics {
  size_t actual_n;
  /**
   * Spheres whose center lies outside the mesh.
   */
  size_t n_out;
  /**
   * Spheres with radius below 0.001 x mesh scale.
   */
  size_t n_tiny;
  /**
   * Volume covered by spheres inside the mesh, relative to the mesh volume.
   */
  double r_in;
  /**
   * Volume covered by spheres outside the mesh, relative to the mesh volume.
   */
  double r_out;
  /**
   * Union volume of the spheres relative to the mesh volume.
   */
  double r_uni;
  /**
   * Mean absolute surface distance in millimetres (mesh units x 1000).
   */
  double d_avg_mm;
  /**
   * Maximum absolute surface distance in millimetres.
   */
  double d_max_mm;
  double mass_abs;
  double mass_rel;
  double com_abs;
  double com_rel;
  double i_abs;
  double i_rel;
} morphit_quality_metrics;

/**
 * Parameters of `morphit_robot_pack_link` (the web API's pack request). Fill
 * with `morphit_pack_params_default`, then change fields.
 */
typedef struct morphit_pack_params {
  /**
   * "MorphIt-V", "MorphIt-S" or "MorphIt-B"; NULL means MorphIt-B.
   */
  const char *variant;
  /**
   * 1 to 200.
   */
  size_t num_spheres;
  /**
   * 1 to 1000.
   */
  size_t iterations;
  /**
   * Random seed; negative draws one at random.
   */
  int64_t seed;
  /**
   * Mesh preparation: merge overlapping bodies (nonzero = on).
   */
  int union_overlapping_bodies;
  /**
   * Mesh preparation: convex hull of each body first (nonzero = on).
   */
  int convex_hull;
  /**
   * The web UI's advanced overrides as a JSON object (e.g.
   * `{"coverage_weight": 2000}`), or NULL.
   */
  const char *advanced_json;
} morphit_pack_params;

/**
 * What `morphit_robot_assemble` changed.
 */
typedef struct morphit_assemble_stats {
  size_t links_with_collisions_replaced;
  size_t mesh_collisions_replaced;
  size_t primitive_collisions_removed;
  size_t sphere_collisions_removed;
  size_t sphere_children_added;
} morphit_assemble_stats;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Library version string, e.g. "0.1.0". Static storage; do not free.
 */
const char *morphit_version(void);

/**
 * Message for the most recent failed call on this thread, or "" if the most
 * recent call succeeded. Valid until the next API call on this thread.
 */
const char *morphit_last_error(void);

/**
 * Set the number of worker threads shared by all sessions. Must be called
 * before the first session is created; returns `MORPHIT_ERR_THREADPOOL` once
 * the pool exists. By default one worker per logical CPU is used.
 */
enum morphit_status morphit_set_num_threads(size_t num_threads);

/**
 * Forward library log messages with level <= `max_level` (1 = error ...
 * 5 = trace) to `callback`, which may be invoked from any thread. Pass NULL to
 * stop forwarding. Fails with `MORPHIT_ERR_STATE` if the host process already
 * installed its own global `tracing` subscriber.
 */
enum morphit_status morphit_set_log_callback(morphit_log_fn callback,
                                             void *user_data,
                                             int max_level);

/**
 * Number of GPU adapters usable for `model.device = "gpu:N"` (0 in a build
 * without GPU support). Enumerating adapters happens once per process.
 */
enum morphit_status morphit_device_count(size_t *count);

/**
 * Name and kind of GPU adapter `index`, e.g. `"NVIDIA RTX A2000 (discrete, Vulkan)"`,
 * as a NUL-terminated string (buffer convention as for the JSON functions).
 */
enum morphit_status morphit_device_name(size_t index, char *buf, size_t capacity, size_t *needed);

/**
 * Load an .obj or .stl file (UTF-8 path). On success `*out` receives a mesh
 * to be released with `morphit_mesh_free`; on failure it is set to NULL.
 */
enum morphit_status morphit_mesh_load(const char *path, struct morphit_mesh **out_mesh);

/**
 * Build a mesh from `num_vertices` xyz triples and `num_triangles` index
 * triples (zero-based, counter-clockwise seen from outside). The data is copied.
 */
enum morphit_status morphit_mesh_from_arrays(const double *xyz,
                                             size_t num_vertices,
                                             const uint32_t *triangles,
                                             size_t num_triangles,
                                             struct morphit_mesh **out_mesh);

/**
 * Load a mesh from file contents in memory: `ext` names the format ("obj",
 * "stl", "ply" or "dae"), `name` (may be NULL) is recorded as the source
 * path. On failure `*out` is set to NULL.
 */
enum morphit_status morphit_mesh_from_bytes(const uint8_t *data,
                                            size_t len,
                                            const char *ext,
                                            const char *name,
                                            struct morphit_mesh **out_mesh);

/**
 * Fill `*out` with the mesh's properties.
 */
enum morphit_status morphit_mesh_get_info(const struct morphit_mesh *mesh,
                                          struct morphit_mesh_info *out_info);

/**
 * Point-in-mesh test for `num_points` xyz triples; `out` receives 1 (inside)
 * or 0 per point. Uses a ray direction that is robust for grid-aligned points.
 */
enum morphit_status morphit_mesh_contains(const struct morphit_mesh *mesh,
                                          const double *xyz,
                                          size_t num_points,
                                          uint8_t *out_inside);

/**
 * The mesh as packing prepares it: overlapping closed bodies unioned when
 * `union_overlapping_bodies` is nonzero, each body replaced by its convex hull
 * first when `convex_hull` is nonzero (the `model.*` keys of the same names).
 * `*out` receives a new mesh (release it with `morphit_mesh_free`); it may
 * share data with `mesh`. The result is computed once per mesh and options.
 */
enum morphit_status morphit_mesh_prepare(const struct morphit_mesh *mesh,
                                         int union_overlapping_bodies,
                                         int convex_hull,
                                         struct morphit_mesh **out_mesh);

/**
 * What `morphit_mesh_prepare` does with the same options, as JSON (the keys
 * of `morphit_session_mesh_prep_json`). Buffer rules as for every string output.
 */
enum morphit_status morphit_mesh_prep_report_json(const struct morphit_mesh *mesh,
                                                  int union_overlapping_bodies,
                                                  int convex_hull,
                                                  char *buf,
                                                  size_t capacity,
                                                  size_t *needed);

/**
 * Write a mesh to `path` (UTF-8), as .obj (exact coordinates) or binary .stl
 * (single precision), chosen by the extension.
 */
enum morphit_status morphit_mesh_save(const struct morphit_mesh *mesh, const char *path);

/**
 * Release a mesh. NULL is ignored. Sessions created from it stay valid.
 */
void morphit_mesh_free(struct morphit_mesh *mesh);

/**
 * Create a config from a preset name ("MorphIt-V", "MorphIt-S", "MorphIt-B",
 * "MorphIt-Obj", "MorphIt-Obj-mass"); NULL selects "MorphIt-B".
 */
enum morphit_status morphit_config_new(const char *preset, struct morphit_config **out_config);

/**
 * Create a config from nested JSON in the result-file layout
 * (`{"model": {...}, "training": {...}, "random_seed": 1}`); missing fields
 * take their defaults.
 */
enum morphit_status morphit_config_from_json(const char *json, struct morphit_config **out_config);

/**
 * Copy a config.
 */
enum morphit_status morphit_config_clone(const struct morphit_config *config,
                                         struct morphit_config **out_config);

/**
 * Set a numeric value by dotted key, e.g. "training.center_lr". An integral
 * value may also be used for integer keys such as "model.num_spheres".
 */
enum morphit_status morphit_config_set_f64(struct morphit_config *config,
                                           const char *key,
                                           double value);

/**
 * Set an integer value by dotted key, e.g. "model.num_spheres" or "random_seed".
 */
enum morphit_status morphit_config_set_i64(struct morphit_config *config,
                                           const char *key,
                                           int64_t value);

/**
 * Set a boolean value (0 = false) by dotted key, e.g. "model.per_sphere_mass".
 */
enum morphit_status morphit_config_set_bool(struct morphit_config *config,
                                            const char *key,
                                            int value);

/**
 * Set a string value by dotted key.
 */
enum morphit_status morphit_config_set_str(struct morphit_config *config,
                                           const char *key,
                                           const char *value);

/**
 * Apply a JSON object of dotted-key updates, e.g.
 * `{"training.iterations": 100, "model.num_spheres": 20}`. All or nothing.
 */
enum morphit_status morphit_config_set_json(struct morphit_config *config,
                                            const char *json_updates);

/**
 * Read a numeric value by dotted key.
 */
enum morphit_status morphit_config_get_f64(const struct morphit_config *config,
                                           const char *key,
                                           double *out_value);

/**
 * Read an integer (or boolean, as 0/1) value by dotted key.
 */
enum morphit_status morphit_config_get_i64(const struct morphit_config *config,
                                           const char *key,
                                           int64_t *out_value);

/**
 * Write the config as nested JSON (NUL-terminated) into `buf`.
 */
enum morphit_status morphit_config_to_json(const struct morphit_config *config,
                                           char *buf,
                                           size_t capacity,
                                           size_t *needed);

/**
 * Release a config. NULL is ignored.
 */
void morphit_config_free(struct morphit_config *config);

/**
 * Create a session: validates the config, samples the mesh and initializes
 * the spheres (this can take a moment for large sample counts). The mesh and
 * config may be freed afterwards.
 */
enum morphit_status morphit_session_new(const struct morphit_mesh *mesh,
                                        const struct morphit_config *config,
                                        struct morphit_session **out_session);

/**
 * Run one iteration. Returns `MORPHIT_OK` after running it (with
 * `info->done` set on the last one) or `MORPHIT_DONE` if no iterations remain.
 * `info` may be NULL. Step-by-step callers finish with `morphit_finalize`.
 */
enum morphit_status morphit_step(struct morphit_session *session, struct morphit_step_info *info);

/**
 * Run all remaining iterations, then finalize (remove spheres whose centers
 * escaped the mesh), like Python's `train()`. `progress` (may be NULL) is
 * called after every iteration without any lock held; it may call the read
 * functions and `morphit_cancel` on this session. Returns `MORPHIT_OK`, or
 * `MORPHIT_ERR_CANCELLED` if cancelled (the session is then not finalized and
 * can be resumed with another `morphit_run`).
 */
enum morphit_status morphit_run(struct morphit_session *session,
                                morphit_progress_fn progress,
                                void *user_data);

/**
 * Ask the active `morphit_run` on this session (or the next one, if none is
 * active) to stop before its next iteration. Never blocks.
 */
enum morphit_status morphit_cancel(struct morphit_session *session);

/**
 * Remove spheres whose centers ended outside the mesh and end the session.
 * Idempotent. `pruned` (may be NULL) receives the number removed.
 */
enum morphit_status morphit_finalize(struct morphit_session *session, size_t *pruned);

/**
 * Release a session. NULL is ignored. Returns `MORPHIT_ERR_BUSY` (and does
 * not free) while `morphit_run` is active on it.
 */
enum morphit_status morphit_session_free(struct morphit_session *session);

/**
 * Progress and status of a session.
 */
enum morphit_status morphit_state(const struct morphit_session *session,
                                  struct morphit_state_info *out_state);

/**
 * Current number of spheres.
 */
enum morphit_status morphit_sphere_count(const struct morphit_session *session, size_t *count);

/**
 * Consistent copy of all sphere data from one moment: `centers` receives 3
 * doubles per sphere, `radii` and `masses` one each. Any of the three may be
 * NULL to skip it; `capacity` is in spheres; `count` receives the number of
 * spheres. All three NULL with capacity 0 is a size query.
 */
enum morphit_status morphit_get_spheres(const struct morphit_session *session,
                                        double *centers,
                                        double *radii,
                                        double *masses,
                                        size_t capacity,
                                        size_t *count);

/**
 * Sphere centers as xyz triples; `capacity` and `*written` count doubles (3 per sphere).
 */
enum morphit_status morphit_get_centers(const struct morphit_session *session,
                                        double *buf,
                                        size_t capacity,
                                        size_t *written);

/**
 * Sphere radii; `capacity` and `*written` count doubles.
 */
enum morphit_status morphit_get_radii(const struct morphit_session *session,
                                      double *buf,
                                      size_t capacity,
                                      size_t *written);

/**
 * Sphere masses (learned, or density x volume); `capacity` and `*written` count doubles.
 */
enum morphit_status morphit_get_masses(const struct morphit_session *session,
                                       double *buf,
                                       size_t capacity,
                                       size_t *written);

/**
 * Details of the most recent iteration; `MORPHIT_ERR_STATE` before the first.
 */
enum morphit_status morphit_get_last_step(const struct morphit_session *session,
                                          struct morphit_step_info *info);

/**
 * Current spheres as JSON in the Python MorphIt result schema
 * (`centers`, `radii`, `masses`, `mesh_path`, `num_spheres`, `per_sphere_mass`,
 * `mesh_prep`, `config`).
 */
enum morphit_status morphit_result_json(const struct morphit_session *session,
                                        char *buf,
                                        size_t capacity,
                                        size_t *needed);

/**
 * Write the current result JSON to a file (UTF-8 path; parent directories are created).
 */
enum morphit_status morphit_result_save(const struct morphit_session *session, const char *path);

/**
 * The session's effective config as nested JSON (includes the mesh path).
 */
enum morphit_status morphit_session_config_json(const struct morphit_session *session,
                                                char *buf,
                                                size_t capacity,
                                                size_t *needed);

/**
 * The device the session's distance searches run on: `"cpu"` or
 * `"gpu:N <adapter name>"`. Never blocks.
 */
enum morphit_status morphit_session_device(const struct morphit_session *session,
                                           char *buf,
                                           size_t capacity,
                                           size_t *needed);

/**
 * What mesh preparation did when the session was created, as JSON with the
 * keys of Python's `MeshPrepReport` plus `convex_hull` and `n_hulled`
 * (`action` is `unchanged`, `unioned`, `hulled`, `skipped` or `disabled`; see
 * `model.union_overlapping_bodies` and `model.convex_hull`). Never blocks.
 */
enum morphit_status morphit_session_mesh_prep_json(const struct morphit_session *session,
                                                   char *buf,
                                                   size_t capacity,
                                                   size_t *needed);

/**
 * Per-iteration training history as JSON (Python `ConvergenceTracker` layout).
 * Unlike the other read functions this waits for a running iteration to
 * finish, and the size may grow between a size query and the copy.
 */
enum morphit_status morphit_history_json(const struct morphit_session *session,
                                         char *buf,
                                         size_t capacity,
                                         size_t *needed);

/**
 * Fill `*out` with the default object-model options.
 */
enum morphit_status morphit_object_options_default(struct morphit_object_options *out_options);

/**
 * The spheres as a URDF: one link per sphere on fixed joints, masses split
 * by volume (as the Python `create_object_urdf.py`). `centers` holds
 * `3 * count` doubles; `options` may be NULL for the defaults. `centroid`
 * (NULL or room for 3 doubles) receives the point the positions are relative
 * to. String buffer rules as everywhere.
 */
enum morphit_status morphit_object_urdf(const double *centers,
                                        const double *radii,
                                        size_t count,
                                        const struct morphit_object_options *options,
                                        char *buf,
                                        size_t capacity,
                                        size_t *needed,
                                        double *centroid);

/**
 * The spheres as MJCF for MuJoCo: a body with one sphere geom per sphere.
 * Arguments as for `morphit_object_urdf`.
 */
enum morphit_status morphit_object_mjcf(const double *centers,
                                        const double *radii,
                                        size_t count,
                                        const struct morphit_object_options *options,
                                        char *buf,
                                        size_t capacity,
                                        size_t *needed,
                                        double *centroid);

/**
 * Fill `*out` with the default quality options.
 */
enum morphit_status morphit_quality_options_default(struct morphit_quality_options *out_options);

/**
 * Score `count` spheres against `mesh` (pass the prepared mesh the spheres
 * were packed on, e.g. from `morphit_session_mesh`). `masses` may be NULL to
 * derive masses from the density; `options` may be NULL for the defaults.
 */
enum morphit_status morphit_evaluate_packing(const struct morphit_mesh *mesh,
                                             const double *centers,
                                             const double *radii,
                                             const double *masses,
                                             size_t count,
                                             const struct morphit_quality_options *options,
                                             struct morphit_quality_metrics *out_metrics);

/**
 * Score a session's current spheres against its prepared mesh. Reads the
 * snapshot, so it may be called while the session runs on another thread.
 */
enum morphit_status morphit_session_evaluate(const struct morphit_session *session,
                                             const struct morphit_quality_options *options,
                                             struct morphit_quality_metrics *out_metrics);

/**
 * The mesh a session packs (after mesh preparation), as a new handle to be
 * released with `morphit_mesh_free`. Never waits for a running iteration.
 */
enum morphit_status morphit_session_mesh(const struct morphit_session *session,
                                         struct morphit_mesh **out_mesh);

/**
 * An empty package; add files with `morphit_robot_add_file`.
 */
enum morphit_status morphit_robot_new(struct morphit_robot **out_robot);

/**
 * Every file under the folder `path` (the package root).
 */
enum morphit_status morphit_robot_from_folder(const char *path, struct morphit_robot **out_robot);

/**
 * A package from the bytes of a `.zip` archive.
 */
enum morphit_status morphit_robot_from_zip(const uint8_t *data,
                                           size_t len,
                                           struct morphit_robot **out_robot);

/**
 * Add (or replace) a file under its path relative to the package root.
 */
enum morphit_status morphit_robot_add_file(struct morphit_robot *robot,
                                           const char *path,
                                           const uint8_t *data,
                                           size_t len);

/**
 * Release a package. NULL is ignored. Sessions created from it stay valid.
 */
void morphit_robot_free(struct morphit_robot *robot);

/**
 * Inspect a URDF of the package: `urdf` selects one by file name, NULL
 * takes the only one. `*out` receives a report to release with
 * `morphit_report_free`.
 */
enum morphit_status morphit_robot_inspect(const struct morphit_robot *robot,
                                          const char *urdf,
                                          struct morphit_robot_report **out_report);

/**
 * The full inspection report as JSON (the web API's `/api/robot/inspect`
 * response: `urdf_path`, `collisions`, `warnings`, ...).
 */
enum morphit_status morphit_report_json(const struct morphit_robot_report *report,
                                        char *buf,
                                        size_t capacity,
                                        size_t *needed);

/**
 * Number of collisions to pack.
 */
enum morphit_status morphit_report_pack_count(const struct morphit_robot_report *report,
                                              size_t *out_count);

/**
 * Pack item `index`: its link name (string buffer rules) and the index of
 * the collision within the link (`collision_index`, may be NULL).
 */
enum morphit_status morphit_report_pack_item(const struct morphit_robot_report *report,
                                             size_t index,
                                             char *link_buf,
                                             size_t capacity,
                                             size_t *needed,
                                             size_t *collision_index);

/**
 * Release a report. NULL is ignored.
 */
void morphit_report_free(struct morphit_robot_report *report);

/**
 * Fill `*out` with the web API's defaults: MorphIt-B, 20 spheres, 200
 * iterations, random seed, union on, convex hull off.
 */
enum morphit_status morphit_pack_params_default(struct morphit_pack_params *out_params);

/**
 * A session packing pack item `index` of `report`. `params` may be NULL for
 * the defaults; `device` may be NULL for "auto". Run it like any session,
 * then record its spheres with `morphit_robot_set_link_result`.
 */
enum morphit_status morphit_robot_pack_link(const struct morphit_robot *robot,
                                            const struct morphit_robot_report *report,
                                            size_t index,
                                            const struct morphit_pack_params *params,
                                            const char *device,
                                            struct morphit_session **out_session);

/**
 * Record the current spheres of `session` as the result of pack item
 * `index` (reads the snapshot; typically after the run finished).
 */
enum morphit_status morphit_robot_set_link_result(const struct morphit_robot *robot,
                                                  const struct morphit_robot_report *report,
                                                  size_t index,
                                                  const struct morphit_session *session);

/**
 * Record the spheres of `link[collision_index]` from a result JSON (the
 * format of `morphit_result_json`, or a Python MorphIt result file).
 */
enum morphit_status morphit_robot_set_link_result_json(const struct morphit_robot *robot,
                                                       const char *link,
                                                       size_t collision_index,
                                                       const char *result_json);

/**
 * Forget every recorded link result.
 */
enum morphit_status morphit_robot_clear_link_results(const struct morphit_robot *robot);

/**
 * The URDF of `report` with every packed collision replaced by sphere links
 * (pack items without a recorded result keep their mesh). `base_color` is
 * "#rrggbb" or NULL; `color_variation` (0..1) spreads the hue over the links.
 * The URDF text follows the string buffer rules; `stats` may be NULL.
 */
enum morphit_status morphit_robot_assemble(const struct morphit_robot *robot,
                                           const struct morphit_robot_report *report,
                                           const char *base_color,
                                           double color_variation,
                                           char *buf,
                                           size_t capacity,
                                           size_t *needed,
                                           struct morphit_assemble_stats *stats);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* MORPHIT_H */
