"""Type stubs of the compiled extension (see the docstrings at runtime)."""

from collections.abc import Callable, Iterator, Mapping, Sequence
from os import PathLike
from typing import Any, Literal, Optional, Union

import numpy as np
import numpy.typing as npt
from typing_extensions import Self, final

_Path = Union[str, PathLike[str]]
_Points = npt.ArrayLike  # (n, 3) float
_Vector = npt.ArrayLike  # (n,) float
_F64_2D = npt.NDArray[np.float64]
_F64_1D = npt.NDArray[np.float64]
_Outcome = Literal["completed", "converged", "cancelled"]

__all__ = [
    "BusyError",
    "CancelledError",
    "Config",
    "ConfigError",
    "Mesh",
    "MeshError",
    "MorphItError",
    "MorphItIOError",
    "PackResult",
    "RobotError",
    "RobotPackage",
    "Session",
    "StateError",
    "StepInfo",
    "_drain_logs",
    "_install_logging",
    "aggregate_overall",
    "devices",
    "evaluate_packing",
    "example_objects",
    "example_robots",
    "link_quality",
    "object_mjcf",
    "object_urdf",
    "pack",
    "presets",
    "set_num_threads",
    "spheres_from_object_urdf",
    "version",
]

class MorphItError(Exception): ...
class MeshError(MorphItError): ...
class StateError(MorphItError): ...
class BusyError(StateError): ...
class CancelledError(MorphItError): ...
class MorphItIOError(MorphItError, OSError): ...

class ConfigError(MorphItError, ValueError):
    key: str

class RobotError(MorphItError, ValueError): ...

@final
class Config:
    def __new__(cls, preset: str = "MorphIt-B") -> Self: ...
    @staticmethod
    def preset(
        name: str = "MorphIt-B",
        *,
        num_spheres: Optional[int] = None,
        iterations: Optional[int] = None,
        seed: Optional[int] = None,
        device: Optional[str] = None,
    ) -> Config: ...
    @staticmethod
    def from_dict(d: Mapping[str, Any]) -> Config: ...
    @staticmethod
    def from_json(text: str) -> Config: ...
    @staticmethod
    def presets() -> list[str]: ...
    def __getitem__(self, key: str, /) -> Any: ...
    def __setitem__(self, key: str, value: Any, /) -> None: ...
    def update(self, updates: Mapping[str, Any]) -> None: ...
    def validate(self) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...
    def to_json(self) -> str: ...
    def copy(self) -> Config: ...
    def __copy__(self) -> Config: ...
    def __deepcopy__(self, memo: Any) -> Config: ...

@final
class Mesh:
    @staticmethod
    def load(path: _Path) -> Mesh: ...
    @staticmethod
    def from_bytes(data: bytes, ext: str, name: Optional[str] = None) -> Mesh: ...
    @staticmethod
    def from_arrays(vertices: _Points, faces: npt.ArrayLike) -> Mesh: ...
    @staticmethod
    def supported_extensions() -> list[str]: ...
    @property
    def vertices(self) -> _F64_2D: ...
    @property
    def faces(self) -> npt.NDArray[np.uint32]: ...
    @property
    def volume(self) -> float: ...
    @property
    def area(self) -> float: ...
    @property
    def bounds(self) -> tuple[list[float], list[float]]: ...
    @property
    def center_mass(self) -> list[float]: ...
    @property
    def inertia(self) -> _F64_2D: ...
    @property
    def winding_flipped(self) -> bool: ...
    @property
    def source_path(self) -> Optional[str]: ...
    def info(self) -> dict[str, Any]: ...
    def contains(self, points: _Points) -> npt.NDArray[np.bool_]: ...
    def prepared(self, union: bool = True, convex_hull: bool = False) -> Mesh: ...
    def prep_report(self, union: bool = True, convex_hull: bool = False) -> dict[str, Any]: ...
    def to_obj(self) -> str: ...
    def to_stl(self) -> bytes: ...
    def save(self, path: _Path) -> None: ...

@final
class PackResult:
    @staticmethod
    def load(path: _Path) -> PackResult: ...
    @staticmethod
    def from_json(text: str) -> PackResult: ...
    @property
    def centers(self) -> _F64_2D: ...
    @property
    def radii(self) -> _F64_1D: ...
    @property
    def masses(self) -> _F64_1D: ...
    @property
    def num_spheres(self) -> int: ...
    @property
    def mesh_path(self) -> str: ...
    @property
    def per_sphere_mass(self) -> bool: ...
    @property
    def mesh_prep(self) -> Optional[dict[str, Any]]: ...
    @property
    def config(self) -> Config: ...
    def to_json(self) -> str: ...
    def to_dict(self) -> dict[str, Any]: ...
    def save(self, path: _Path) -> None: ...
    def __len__(self) -> int: ...

@final
class StepInfo:
    @property
    def iteration(self) -> int: ...
    @property
    def total_loss(self) -> float: ...
    @property
    def weighted_losses(self) -> dict[str, float]: ...
    @property
    def raw_losses(self) -> dict[str, float]: ...
    @property
    def position_grad_mag(self) -> float: ...
    @property
    def radius_grad_mag(self) -> float: ...
    @property
    def num_spheres(self) -> int: ...
    @property
    def projected(self) -> int: ...
    @property
    def density_control(self) -> Optional[dict[str, int]]: ...
    @property
    def done(self) -> bool: ...
    @property
    def converged(self) -> bool: ...
    @property
    def seconds(self) -> float: ...

@final
class Session:
    def __new__(cls, mesh: Mesh, config: Config) -> Self: ...
    def step(self) -> StepInfo: ...
    def __iter__(self) -> Iterator[StepInfo]: ...
    def __next__(self) -> StepInfo: ...
    def run(self, callback: Optional[Callable[[StepInfo], Optional[bool]]] = None, *, every: int = 1) -> _Outcome: ...
    def cancel(self) -> None: ...
    def finalize(self) -> int: ...
    def result(self) -> PackResult: ...
    @property
    def iteration(self) -> int: ...
    @property
    def total_iterations(self) -> int: ...
    @property
    def state(self) -> Literal["running", "converged", "completed", "finalized"]: ...
    @property
    def is_done(self) -> bool: ...
    @property
    def is_running(self) -> bool: ...
    @property
    def centers(self) -> _F64_2D: ...
    @property
    def radii(self) -> _F64_1D: ...
    @property
    def masses(self) -> _F64_1D: ...
    @property
    def num_spheres(self) -> int: ...
    @property
    def last_step(self) -> Optional[StepInfo]: ...
    @property
    def density_passes(self) -> int: ...
    @property
    def pruned(self) -> int: ...
    @property
    def device(self) -> str: ...
    @property
    def gpu_error(self) -> Optional[str]: ...
    @property
    def config(self) -> Config: ...
    @property
    def mesh(self) -> Mesh: ...
    @property
    def mesh_prep(self) -> dict[str, Any]: ...
    @property
    def init_info(self) -> dict[str, Any]: ...
    def history(self) -> dict[str, Any]: ...
    def samples(self) -> tuple[_F64_2D, _F64_2D]: ...

@final
class RobotPackage:
    def __new__(cls) -> Self: ...
    @staticmethod
    def from_folder(path: _Path) -> RobotPackage: ...
    @staticmethod
    def from_zip(archive: Union[bytes, _Path]) -> RobotPackage: ...
    @staticmethod
    def from_files(files: Mapping[str, bytes]) -> RobotPackage: ...
    def add_file(self, path: str, data: bytes) -> str: ...
    def files(self) -> list[str]: ...
    def urdfs(self) -> list[str]: ...
    def inspect(self, urdf: Optional[str] = None) -> dict[str, Any]: ...
    def link_poses(self, urdf: Optional[str] = None) -> dict[str, dict[str, list[float]]]: ...
    def mesh(self, path: str) -> Mesh: ...
    def pack_link(
        self,
        item: Mapping[str, Any],
        *,
        variant: str = "MorphIt-B",
        num_spheres: int = 20,
        iterations: int = 200,
        seed: Optional[int] = None,
        advanced: Optional[Mapping[str, Any]] = None,
        union_overlapping_bodies: bool = True,
        convex_hull: bool = False,
        device: str = "auto",
    ) -> Session: ...
    def pack_all(
        self,
        *,
        urdf: Optional[str] = None,
        variant: str = "MorphIt-B",
        num_spheres: int = 20,
        iterations: int = 200,
        seed: Optional[int] = None,
        advanced: Optional[Mapping[str, Any]] = None,
        union_overlapping_bodies: bool = True,
        convex_hull: bool = False,
        device: str = "auto",
        callback: Optional[Callable[[str, int, StepInfo], Optional[bool]]] = None,
    ) -> dict[tuple[str, int], PackResult]: ...
    def set_link_result(self, link: str, index: int, result: PackResult) -> None: ...
    def link_results(self) -> list[tuple[str, int]]: ...
    def clear_link_results(self) -> None: ...
    def assemble(
        self, urdf: Optional[str] = None, *, base_color: Optional[str] = None, color_variation: float = 0.0
    ) -> tuple[str, dict[str, Any]]: ...

def version() -> str: ...
def presets() -> list[str]: ...
def devices() -> list[dict[str, Any]]: ...
def set_num_threads(n: int) -> None: ...
def pack(mesh: Mesh, config: Optional[Config] = None) -> PackResult: ...
def example_objects() -> list[dict[str, Any]]: ...
def example_robots() -> list[dict[str, Any]]: ...
def object_urdf(
    centers: _Points,
    radii: _Vector,
    *,
    name: Optional[str] = None,
    color: Optional[str] = None,
    total_mass: Optional[float] = None,
    anchored: bool = False,
    decimals: Optional[int] = None,
) -> tuple[str, list[float]]: ...
def object_mjcf(
    centers: _Points,
    radii: _Vector,
    *,
    name: Optional[str] = None,
    color: Optional[str] = None,
    total_mass: Optional[float] = None,
    anchored: bool = False,
    decimals: Optional[int] = None,
) -> tuple[str, list[float]]: ...
def spheres_from_object_urdf(text: str) -> tuple[_F64_2D, _F64_1D]: ...
def evaluate_packing(mesh: Mesh, result: PackResult, **options: Any) -> dict[str, Any]: ...
def link_quality(
    mesh: Mesh, link_name: str, collision_index: int, centers: _Points, radii: _Vector
) -> dict[str, Any]: ...
def aggregate_overall(links: Sequence[Mapping[str, Any]]) -> dict[str, Any]: ...
def _install_logging(level: str = "INFO") -> bool: ...
def _drain_logs() -> list[tuple[int, str, str]]: ...
